// flow-typed signature: 799c34975d536c380adaeacd0a237432
// flow-typed version: <<STUB>>/simplify-js_v1.2.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplify-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplify-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplify-js/simplify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplify-js/simplify.js' {
  declare module.exports: $Exports<'simplify-js/simplify'>;
}
